### ISSUE TITLE
 Unknown field 'description' on type 'StripeSkuProduct'. 

### ISSUE THREAD

**Issue by bahoffman** [brxck/gatsby-starter-stripe#2]
I Created a new project using this starter and Configured my API Keys with no issues. However, I get the following errors - 
--
success open and validate gatsby-configs — 1.846 s
success load plugins — 22.471 s
success onPreInit — 0.010 s
success initialize cache — 0.074 s
success copy gatsby files — 1.218 s
success onPreBootstrap — 0.095 s
⠄ source and transform nodes✕ We were unable to download images that Stripe was pointing at
Error: We were unable to create a valid Gatsby file node

⠠ source and transform nodesFailed to process remote content https://files.stripe.com/files/f_test_MvxUIHD9YnwN8hharE8i9Or1
Downloading remote files [==============================] 1/1 0.0 secs 100%
✕ We were unable to download files that Stripe was hosting
URL: https://files.stripe.com/files/f_test_MvxUIHD9YnwN8hharE8i9Or1
Error: We were unable to create a valid Gatsby file node

✕ We were unable to download images that Stripe was pointing at
Error: We were unable to create a valid Gatsby file node

⠁ source and transform nodesFailed to process remote content https://files.stripe.com/files/f_test_ZHMenNxOZqp8bT0G8JTxUVIH
Downloading remote files [==============================] 2/2 0.7 secs 100%
✕ We were unable to download files that Stripe was hosting
URL: https://files.stripe.com/files/f_test_ZHMenNxOZqp8bT0G8JTxUVIH
Error: We were unable to create a valid Gatsby file node

✕ We were unable to download images that Stripe was pointing at
Error: We were unable to create a valid Gatsby file node

success source and transform nodes — 3.458 s
success building schema — 0.997 s
success createPages — 0.091 s
success createPagesStatefully — 0.117 s
success onPreExtractQueries — 0.083 s
success update schema — 0.080 s
error GraphQL Error Encountered 1 error(s):
- Unknown field 'description' on type 'StripeSkuProduct'.

      file: C:/Users/user/Documents/webDev/my-gatsby-stripe-site/src/components/ProductsProvider.js

success extract queries from components — 0.622 s
⠁ (node:5416) DeprecationWarning: Passing lineNumber and colNumber is deprecated to @babel/code-frame. Please use `codeFrameColumns`.
success run graphql queries — 0.035 s — 5/5 151.73 queries/second
success write out page data — 0.124 s
success write out redirect data — 0.006 s
success Build manifest and related icons — 0.376 s
success onPostBootstrap — 0.383 s

info bootstrap finished - 124.113 s

[HPM] Proxy created: /  ->  http://localhost:9000
[HPM] Proxy rewrite rule created: "/.netlify/functions/" ~> ""
i ｢wdm｣: wait until bundle finished: /
 DONE  Compiled successfully in 16567ms
---
My STRIPE logs indicate - 
Response body
{
  "error": {
    "message": "You provided an API key, but the requested endpoint does not require authentication. Try sending your request again without the 'Authorization' header.",
    "type": "invalid_request_error"
  }
}

Thank you.

**Comment by brxck** [comment]
> You provided an API key, but the requested endpoint does not require authentication. Try sending your request again without the 'Authorization' header.

This looks like an issue that was fixed recently in [gatsby-source-stripe](https://github.com/njosefbeck/gatsby-source-stripe). This has to do with the failing file downloads in the logs. Are you using the new version of Stripe Checkout? Try updating that package, I'll get around to updating it in the starter.

> Unknown field 'description' on type 'StripeSkuProduct'.

Not sure what would be causing this without more info. Are there descriptions on your Stripe products?

**Comment by cn2amz** [comment]
I have the same problem in my local development environment.
below is my info:

system: windows 10
browser: chrome 72.0.3626.109
E:\learning\gatsby\gatsby-stripe-shop (master -> origin)
$ node -v
v10.15.3

E:\learning\gatsby\gatsby-stripe-shop (master -> origin)
$ npm -v
6.4.1

E:\learning\gatsby\gatsby-stripe-shop (master -> origin)
$ cat package.json
{
  "name": "gatsby-starter-stripe",
  "private": true,
  "description": "A minimal starter to create a storefront with Stripe & Gatsby.",
  "version": "0.1.0",
  "author": "Brock McElroy (https://brockmcelroy.com)",
  "dependencies": {
    "dotenv-webpack": "^1.7.0",
    "gatsby": "^2.7.1",
    "gatsby-image": "^2.1.1",
    "gatsby-plugin-manifest": "^2.1.1",
    "gatsby-plugin-offline": "^2.1.1",
    "gatsby-plugin-react-helmet": "^3.0.12",
    "gatsby-plugin-sharp": "^2.1.1",
    "gatsby-source-filesystem": "^2.0.37",
    "gatsby-source-stripe": "^2.2.2",
    "gatsby-transformer-sharp": "^2.1.19",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-helmet": "^5.2.1",
    "react-stripe-checkout": "^2.6.3",
    "slug": "^1.1.0",
    "stripe": "^7.1.0",
    "typescript": "^3.4.5"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "develop": "gatsby develop",
    "start": "run-p start:**",
    "start:app": "npm run develop",
    "start:lambda": "netlify-lambda serve -c ./webpack.development.js src/functions",
    "build": "run-p build:**",
    "build:app": "gatsby build",
    "build:lambda": "netlify-lambda build -c ./webpack.production.js src/functions"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/brxck/gatsby-starter-stripe"
  },
  "bugs": {
    "url": "https://github.com/brxck/gatsby-starter-stripe/issues"
  },
  "devDependencies": {
    "eslint": "^5.16.0",
    "eslint-config-gatsby-standard": "^2.2.0",
    "eslint-plugin-react": "^7.13.0",
    "http-proxy-middleware": "^0.19.1",
    "netlify-lambda": "^1.4.13",
    "npm-run-all": "^4.1.5",
    "prettier": "^1.17.1"
  }
}

error messages as follows:
E:\learning\gatsby\gatsby-stripe-shop (master -> origin)
$ gatsby develop
success open and validate gatsby-configs - 0.102 s
success load plugins - 2.219 s
success onPreInit - 0.008 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success initialize cache - 0.053 s
success copy gatsby files - 0.126 s
success onPreBootstrap - 0.019 s
✕ We were unable to download images that Stripe was pointing at
Error: We were unable to create a valid Gatsby file node

warn Failed to process remote content
⠀
✕ We were unable to download files that Stripe was hosting
URL: https://files.stripe.com/links/fl_test_eAxWFIeJWUcuCZipvjTzKwwD
Error: We were unable to create a valid Gatsby file node

✕ We were unable to download images that Stripe was pointing at
Error: We were unable to create a valid Gatsby file node

success source and transform nodes - 3.674 s
success building schema - 0.406 s
success createPages - 0.032 s
success createPagesStatefully - 0.041 s
success onPreExtractQueries - 0.007 s
success update schema - 0.036 s
error GraphQL Error Encountered 1 error(s):
- Unknown field 'description' on type 'StripeSkuProduct'.

      file: E:/learning/gatsby/gatsby-stripe-shop/src/components/ProductsProvider.js



success extract queries from components - 0.373 s
success run static queries - 0.006 s
error (node:12884) DeprecationWarning: Passing lineNumber and colNumber is deprecated to
success run page queries - 0.054 s — 5/5 121.92 queries/second
success write out page data - 0.016 s
success write out redirect data - 0.005 s
success Build manifest and related icons - 0.162 s
success onPostBootstrap - 0.173 s
⠀
info bootstrap finished - 23.029 s
⠀
info [HPM] Proxy created: /  ->  http://localhost:9000
info [HPM] Proxy rewrite rule created: "/.netlify/functions/" ~> ""
 DONE  Compiled successfully in 4813ms                                              14:06:38⠀
⠀
You can now view gatsby-starter-stripe in the browser.

**Comment by brxck** [comment]
I believe any issues should be fixed by the new gatsby-source-stripe version, and required fields are now clarified in the README thanks to #12.
